export const API_URL = 'http://hn.algolia.com/api/v1/search?tags=front_page';

export const API_COMMENT =
  'http://hn.algolia.com/api/v1/search?tags=comment,story_';

const ANSWER = {
  hits: [
    {
      created_at: '2022-12-07T18:06:58.000Z',
      title: 'Apple introduces end-to-end encryption for backups',
      url: 'https://support.apple.com/en-us/HT202303#advanced',
      author: 'frizlab',
      points: 1460,
      story_text: null,
      comment_text: null,
      num_comments: 958,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670436418,
      _tags: ['story', 'author_frizlab', 'story_33897793', 'front_page'],
      objectID: '33897793',
      _highlightResult: {
        title: {
          value: 'Apple introduces end-to-end encryption for backups',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value: 'https://support.apple.com/en-us/HT202303#advanced',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'frizlab',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T04:42:49.000Z',
      title:
        'I liberate the ending to Minecraft from Microsoft and give it to you',
      url: 'https://theeggandtherock.substack.com/p/i-wrote-a-story-for-a-friend',
      author: 'dihydro',
      points: 852,
      story_text: null,
      comment_text: null,
      num_comments: 598,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670474569,
      _tags: ['story', 'author_dihydro', 'story_33904251', 'front_page'],
      objectID: '33904251',
      _highlightResult: {
        title: {
          value:
            'I liberate the ending to Minecraft from Microsoft and give it to you',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value:
            'https://theeggandtherock.substack.com/p/i-wrote-a-story-for-a-friend',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'dihydro',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T04:06:36.000Z',
      title: "You don't need live chat on your website",
      url: 'https://timharek.no/blog/you-dont-need-chat-on-your-site/',
      author: '5amdotis',
      points: 405,
      story_text: null,
      comment_text: null,
      num_comments: 193,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670472396,
      _tags: ['story', 'author_5amdotis', 'story_33904017', 'front_page'],
      objectID: '33904017',
      _highlightResult: {
        title: {
          value: "You don't need live chat on your website",
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value: 'https://timharek.no/blog/you-dont-need-chat-on-your-site/',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: '5amdotis',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T15:05:49.000Z',
      title:
        'Everything SBF is doing is in singular pursuit of not going to jail',
      url: 'https://newsletter.mollywhite.net/p/everything-sam-bankman-fried-is-doing',
      author: 'mfbx9da4',
      points: 272,
      story_text: null,
      comment_text: null,
      num_comments: 251,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670511949,
      _tags: ['story', 'author_mfbx9da4', 'story_33908577', 'front_page'],
      objectID: '33908577',
      _highlightResult: {
        title: {
          value:
            'Everything SBF is doing is in singular pursuit of not going to jail',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value:
            'https://newsletter.mollywhite.net/p/everything-sam-bankman-fried-is-doing',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'mfbx9da4',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T12:22:05.000Z',
      title: 'PHP 8.2',
      url: 'https://www.php.net/releases/8.2/en.php',
      author: 'TimWolla',
      points: 201,
      story_text: null,
      comment_text: null,
      num_comments: 185,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670502125,
      _tags: ['story', 'author_TimWolla', 'story_33907096', 'front_page'],
      objectID: '33907096',
      _highlightResult: {
        title: {
          value: 'PHP 8.2',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value: 'https://www.php.net/releases/8.2/en.php',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'TimWolla',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T04:53:58.000Z',
      title: 'Fermilab/CERN recommendation for Linux distribution',
      url: 'https://news.fnal.gov/2022/12/fermilab-cern-recommendation-for-linux-distribution/',
      author: 'jaboutboul',
      points: 200,
      story_text: null,
      comment_text: null,
      num_comments: 110,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670475238,
      _tags: ['story', 'author_jaboutboul', 'story_33904336', 'front_page'],
      objectID: '33904336',
      _highlightResult: {
        title: {
          value: 'Fermilab/CERN recommendation for Linux distribution',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value:
            'https://news.fnal.gov/2022/12/fermilab-cern-recommendation-for-linux-distribution/',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'jaboutboul',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T12:30:34.000Z',
      title: 'A Christmas tree bauble that plays Doom',
      url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      author: 'distcs',
      points: 174,
      story_text: null,
      comment_text: null,
      num_comments: 22,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670502634,
      _tags: ['story', 'author_distcs', 'story_33907158', 'front_page'],
      objectID: '33907158',
      _highlightResult: {
        title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'distcs',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T02:39:33.000Z',
      title: 'Intel is using DXVK for their Windows Arc GPU DX9 drivers',
      url: 'https://www.gamingonlinux.com/2022/12/intel-using-dxvk-part-of-steam-proton-for-their-windows-arc-gpu-dx-9-drivers/',
      author: 'pantalaimon',
      points: 163,
      story_text: null,
      comment_text: null,
      num_comments: 63,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670467173,
      _tags: ['story', 'author_pantalaimon', 'story_33903420', 'front_page'],
      objectID: '33903420',
      _highlightResult: {
        title: {
          value: 'Intel is using DXVK for their Windows Arc GPU DX9 drivers',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value:
            'https://www.gamingonlinux.com/2022/12/intel-using-dxvk-part-of-steam-proton-for-their-windows-arc-gpu-dx-9-drivers/',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'pantalaimon',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T12:43:26.000Z',
      title: 'Ideas that changed my life',
      url: 'https://collabfund.com/blog/ideas-that-changed-my-life/',
      author: 'RickJWagner',
      points: 146,
      story_text: null,
      comment_text: null,
      num_comments: 29,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670503406,
      _tags: ['story', 'author_RickJWagner', 'story_33907245', 'front_page'],
      objectID: '33907245',
      _highlightResult: {
        title: {
          value: 'Ideas that changed my life',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value: 'https://collabfund.com/blog/ideas-that-changed-my-life/',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'RickJWagner',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T11:00:01.000Z',
      title: 'Tell HN: Travis CI is seemingly compromised (once again)',
      url: null,
      author: 'spondyl',
      points: 127,
      story_text:
        'A number of Travis CI users appear to have had Travis CI tokens revoked by Github in response to suspicious activity surrounding token.<p>Travis themselves have still not issued any notice or acknowledged this incident so it&#x27;s worth letting the community know if they weren&#x27;t already aware.<p>From memory, this will be the second breach in 2022 (<a href="https:&#x2F;&#x2F;blog.aquasec.com&#x2F;travis-ci-security" rel="nofollow">https:&#x2F;&#x2F;blog.aquasec.com&#x2F;travis-ci-security</a>) in addition to last year&#x27;s secret exposure (<a href="https:&#x2F;&#x2F;arstechnica.com&#x2F;information-technology&#x2F;2021&#x2F;09&#x2F;travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects&#x2F;" rel="nofollow">https:&#x2F;&#x2F;arstechnica.com&#x2F;information-technology&#x2F;2021&#x2F;09&#x2F;travi...</a>)<p>---<p>A sampling of users on Twitter who have run into this issue:<p><a href="https:&#x2F;&#x2F;twitter.com&#x2F;peter_szilagyi&#x2F;status&#x2F;1600593274108055559" rel="nofollow">https:&#x2F;&#x2F;twitter.com&#x2F;peter_szilagyi&#x2F;status&#x2F;160059327410805555...</a><p><a href="https:&#x2F;&#x2F;twitter.com&#x2F;yaqwsx_cz&#x2F;status&#x2F;1600599797118996491" rel="nofollow">https:&#x2F;&#x2F;twitter.com&#x2F;yaqwsx_cz&#x2F;status&#x2F;1600599797118996491</a><p><a href="https:&#x2F;&#x2F;twitter.com&#x2F;samonchain&#x2F;status&#x2F;1600611567606775808" rel="nofollow">https:&#x2F;&#x2F;twitter.com&#x2F;samonchain&#x2F;status&#x2F;1600611567606775808</a><p><a href="https:&#x2F;&#x2F;twitter.com&#x2F;dzarda_cz&#x2F;status&#x2F;1600613369408634886" rel="nofollow">https:&#x2F;&#x2F;twitter.com&#x2F;dzarda_cz&#x2F;status&#x2F;1600613369408634886</a><p><a href="https:&#x2F;&#x2F;twitter.com&#x2F;samonchain&#x2F;status&#x2F;1600611567606775808" rel="nofollow">https:&#x2F;&#x2F;twitter.com&#x2F;samonchain&#x2F;status&#x2F;1600611567606775808</a><p>---<p>An example notice being sent out by Github (in lieu of Travis themselves taking any action):<p>&gt; Hi {username}<p>&gt; We&#x27;re writing to let you know that we observed suspicious activity that suggests a threat actor used a Personal Access Token (PAT) associated with your account to access private repository metadata.<p>&gt; Out of an abundance of caution, we reset your account password and revoked all of your Personal Access Tokens (classic), OAuth App tokens, and GitHub App tokens to protect your account, {username}.',
      comment_text: null,
      num_comments: 36,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670497201,
      _tags: ['story', 'author_spondyl', 'story_33906591', 'front_page'],
      objectID: '33906591',
      _highlightResult: {
        title: {
          value: 'Tell HN: Travis CI is seemingly compromised (once again)',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'spondyl',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_text: {
          value:
            'A number of Travis CI users appear to have had Travis CI tokens revoked by Github in response to suspicious activity surrounding token.<p>Travis themselves have still not issued any notice or acknowledged this incident so it\'s worth letting the community know if they weren\'t already aware.<p>From memory, this will be the second breach in 2022 (<a href="https://blog.aquasec.com/travis-ci-security" rel="nofollow">https://blog.aquasec.com/travis-ci-security</a>) in addition to last year\'s secret exposure (<a href="https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/" rel="nofollow">https://arstechnica.com/information-technology/2021/09/travi...</a>)<p>---<p>A sampling of users on Twitter who have run into this issue:<p><a href="https://twitter.com/peter_szilagyi/status/1600593274108055559" rel="nofollow">https://twitter.com/peter_szilagyi/status/160059327410805555...</a><p><a href="https://twitter.com/yaqwsx_cz/status/1600599797118996491" rel="nofollow">https://twitter.com/yaqwsx_cz/status/1600599797118996491</a><p><a href="https://twitter.com/samonchain/status/1600611567606775808" rel="nofollow">https://twitter.com/samonchain/status/1600611567606775808</a><p><a href="https://twitter.com/dzarda_cz/status/1600613369408634886" rel="nofollow">https://twitter.com/dzarda_cz/status/1600613369408634886</a><p><a href="https://twitter.com/samonchain/status/1600611567606775808" rel="nofollow">https://twitter.com/samonchain/status/1600611567606775808</a><p>---<p>An example notice being sent out by Github (in lieu of Travis themselves taking any action):<p>&gt; Hi {username}<p>&gt; We\'re writing to let you know that we observed suspicious activity that suggests a threat actor used a Personal Access Token (PAT) associated with your account to access private repository metadata.<p>&gt; Out of an abundance of caution, we reset your account password and revoked all of your Personal Access Tokens (classic), OAuth App tokens, and GitHub App tokens to protect your account, {username}.',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T10:06:29.000Z',
      title: 'What comes up when you flush',
      url: 'https://www.colorado.edu/today/2022/12/08/cu-scientists-shine-light-what-comes-when-you-flush',
      author: 'sciencefreak939',
      points: 124,
      story_text: null,
      comment_text: null,
      num_comments: 119,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670493989,
      _tags: [
        'story',
        'author_sciencefreak939',
        'story_33906251',
        'front_page',
      ],
      objectID: '33906251',
      _highlightResult: {
        title: {
          value: 'What comes up when you flush',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value:
            'https://www.colorado.edu/today/2022/12/08/cu-scientists-shine-light-what-comes-when-you-flush',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'sciencefreak939',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T12:55:35.000Z',
      title: 'Ask HN: Are things getting more convenient but less satisfying?',
      url: null,
      author: 'agomez314',
      points: 118,
      story_text:
        'I read a post on HN recently where a guy in his teens used to visit a construction site to watch how peopled worked and even help them for small fee. Now he could just watch a YouTube video about it in 10 different ways but the experience differs in that the workers used to treat him well and converse with him, which obviously made him a deep impression.<p>So I&#x27;d be interested to generalize this: with things getting more and more digital and disembodied (ahem, ChatGPT), does it produce convenience at the expense of contentment?',
      comment_text: null,
      num_comments: 124,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670504135,
      _tags: [
        'story',
        'author_agomez314',
        'story_33907357',
        'ask_hn',
        'front_page',
      ],
      objectID: '33907357',
      _highlightResult: {
        title: {
          value:
            'Ask HN: Are things getting more convenient but less satisfying?',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'agomez314',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_text: {
          value:
            "I read a post on HN recently where a guy in his teens used to visit a construction site to watch how peopled worked and even help them for small fee. Now he could just watch a YouTube video about it in 10 different ways but the experience differs in that the workers used to treat him well and converse with him, which obviously made him a deep impression.<p>So I'd be interested to generalize this: with things getting more and more digital and disembodied (ahem, ChatGPT), does it produce convenience at the expense of contentment?",
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T10:50:05.000Z',
      title:
        'Show HN: Ezy – open-source gRPC client, alternative to Postman and Insomnia',
      url: 'https://github.com/getezy/ezy/releases/tag/v1.0.0-beta.13.2',
      author: 'notmedia',
      points: 118,
      story_text:
        'In this release I have concentrated on user experience:<p>- Full support of shortcuts\n- Reworked collections management\n- Notifications\n- Improved UX<p>gRPC clients I’ve worked with had drawbacks and didn’t fit my use-case in a way I was expecting, since I’ve started working with gRPC 3+ years ago.<p>Since then, I wanted a tool that fits any need in gRPC world. This is why I created ezy.<p>Compared to Insomnia and Postman, ezy offers better streams support, allows you to use Server-Side and Mutual TLS with custom TLS certificates, works with gRPC-Web and has a more slick UI&#x2F;UX.<p>If you are looking for a gRPC&#x2F;gRPC-Web client which fits your needs, give ezy a chance!<p>I’d love to hear your feedback and answer any questions regarding ezy.',
      comment_text: null,
      num_comments: 17,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670496605,
      _tags: [
        'story',
        'author_notmedia',
        'story_33906520',
        'show_hn',
        'front_page',
      ],
      objectID: '33906520',
      _highlightResult: {
        title: {
          value:
            'Show HN: Ezy – open-source gRPC client, alternative to Postman and Insomnia',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value: 'https://github.com/getezy/ezy/releases/tag/v1.0.0-beta.13.2',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'notmedia',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_text: {
          value:
            'In this release I have concentrated on user experience:<p>- Full support of shortcuts\n- Reworked collections management\n- Notifications\n- Improved UX<p>gRPC clients I’ve worked with had drawbacks and didn’t fit my use-case in a way I was expecting, since I’ve started working with gRPC 3+ years ago.<p>Since then, I wanted a tool that fits any need in gRPC world. This is why I created ezy.<p>Compared to Insomnia and Postman, ezy offers better streams support, allows you to use Server-Side and Mutual TLS with custom TLS certificates, works with gRPC-Web and has a more slick UI/UX.<p>If you are looking for a gRPC/gRPC-Web client which fits your needs, give ezy a chance!<p>I’d love to hear your feedback and answer any questions regarding ezy.',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T04:20:50.000Z',
      title:
        'Pulling MikroTik into the Limelight Demystifying and Jailbreaking RouterS',
      url: 'https://margin.re/2022/06/pulling-mikrotik-into-the-limelight/',
      author: '882542F3884314B',
      points: 115,
      story_text: null,
      comment_text: null,
      num_comments: 46,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670473250,
      _tags: [
        'story',
        'author_882542F3884314B',
        'story_33904105',
        'front_page',
      ],
      objectID: '33904105',
      _highlightResult: {
        title: {
          value:
            'Pulling MikroTik into the Limelight Demystifying and Jailbreaking RouterS',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value:
            'https://margin.re/2022/06/pulling-mikrotik-into-the-limelight/',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: '882542F3884314B',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T15:05:45.000Z',
      title: 'Codon: A high-performance Python compiler using LLVM',
      url: 'https://github.com/exaloop/codon',
      author: 'arshajii',
      points: 94,
      story_text: null,
      comment_text: null,
      num_comments: 39,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670511945,
      _tags: ['story', 'author_arshajii', 'story_33908576', 'front_page'],
      objectID: '33908576',
      _highlightResult: {
        title: {
          value: 'Codon: A high-performance Python compiler using LLVM',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value: 'https://github.com/exaloop/codon',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'arshajii',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T14:38:08.000Z',
      title: "The Sad Story of Heisenberg's Doctoral Oral Exam (1998)",
      url: 'https://www.aps.org/publications/apsnews/199801/heisenberg.cfm',
      author: 'occamschainsaw',
      points: 88,
      story_text: null,
      comment_text: null,
      num_comments: 53,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670510288,
      _tags: ['story', 'author_occamschainsaw', 'story_33908280', 'front_page'],
      objectID: '33908280',
      _highlightResult: {
        title: {
          value: "The Sad Story of Heisenberg's Doctoral Oral Exam (1998)",
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value:
            'https://www.aps.org/publications/apsnews/199801/heisenberg.cfm',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'occamschainsaw',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-07T02:42:16.000Z',
      title: 'A Museum Dedicated to Mistranslated Japanese Phrases',
      url: 'https://www.spoon-tamago.com/2022/12/06/museum-of-wonky-english/',
      author: 'zdw',
      points: 85,
      story_text: null,
      comment_text: null,
      num_comments: 54,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670380936,
      _tags: ['story', 'author_zdw', 'story_33890061', 'front_page'],
      objectID: '33890061',
      _highlightResult: {
        title: {
          value: 'A Museum Dedicated to Mistranslated Japanese Phrases',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value:
            'https://www.spoon-tamago.com/2022/12/06/museum-of-wonky-english/',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'zdw',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-11-27T19:18:16.000Z',
      title: 'Emacs Lisp shorthands as namespacing system',
      url: 'https://andreyorst.gitlab.io/posts/2022-11-01-emacs-lisp-shorthands-as-namespacing-system/',
      author: 'gjvc',
      points: 78,
      story_text: null,
      comment_text: null,
      num_comments: 15,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1669576696,
      _tags: ['story', 'author_gjvc', 'story_33765735', 'front_page'],
      objectID: '33765735',
      _highlightResult: {
        title: {
          value: 'Emacs Lisp shorthands as namespacing system',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value:
            'https://andreyorst.gitlab.io/posts/2022-11-01-emacs-lisp-shorthands-as-namespacing-system/',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'gjvc',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-07T15:42:45.000Z',
      title: 'Vanuatu has been knocked offline for over a month',
      url: 'https://www.npr.org/2022/12/06/1140752192/the-pacific-island-nation-of-vanuatu-has-been-knocked-offline-for-more-than-a-mo',
      author: 'erehweb',
      points: 76,
      story_text: null,
      comment_text: null,
      num_comments: 17,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670427765,
      _tags: ['story', 'author_erehweb', 'story_33895622', 'front_page'],
      objectID: '33895622',
      _highlightResult: {
        title: {
          value: 'Vanuatu has been knocked offline for over a month',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value:
            'https://www.npr.org/2022/12/06/1140752192/the-pacific-island-nation-of-vanuatu-has-been-knocked-offline-for-more-than-a-mo',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'erehweb',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T12:46:55.000Z',
      title: '‘Significant overload’ caused Norway’s timber bridge collapse',
      url: 'https://www.newcivilengineer.com/latest/significant-overload-caused-norways-timber-bridge-collapse-05-12-2022/',
      author: 'mjmasn',
      points: 71,
      story_text: null,
      comment_text: null,
      num_comments: 42,
      story_id: null,
      story_title: null,
      story_url: null,
      parent_id: null,
      created_at_i: 1670503615,
      _tags: ['story', 'author_mjmasn', 'story_33907276', 'front_page'],
      objectID: '33907276',
      _highlightResult: {
        title: {
          value:
            '‘Significant overload’ caused Norway’s timber bridge collapse',
          matchLevel: 'none',
          matchedWords: [],
        },
        url: {
          value:
            'https://www.newcivilengineer.com/latest/significant-overload-caused-norways-timber-bridge-collapse-05-12-2022/',
          matchLevel: 'none',
          matchedWords: [],
        },
        author: {
          value: 'mjmasn',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
  ],
  nbHits: 45,
  page: 0,
  nbPages: 3,
  hitsPerPage: 20,
  exhaustiveNbHits: true,
  exhaustiveTypo: true,
  exhaustive: {
    nbHits: true,
    typo: true,
  },
  query: '',
  params:
    'advancedSyntax=true&analytics=true&analyticsTags=backend&tags=front_page',
  processingTimeMS: 3,
  processingTimingsMS: {
    afterFetch: {
      total: 3,
    },
    total: 3,
  },
};

const COMMENTS = {
  hits: [
    {
      created_at: '2022-12-08T18:47:54.000Z',
      title: null,
      url: null,
      author: 'detaro',
      points: null,
      story_text: null,
      comment_text:
        '... that&#x27;s an new display stuffed in the shell of a pregnancy test, running the game on an external processor: <a href="https:&#x2F;&#x2F;twitter.com&#x2F;Foone&#x2F;status&#x2F;1302453805057896448" rel="nofollow">https:&#x2F;&#x2F;twitter.com&#x2F;Foone&#x2F;status&#x2F;1302453805057896448</a>',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33911452,
      created_at_i: 1670525274,
      _tags: ['comment', 'author_detaro', 'story_33907158'],
      objectID: '33911515',
      _highlightResult: {
        author: {
          value: 'detaro',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value:
            '... that\'s an new display stuffed in the shell of a pregnancy test, running the game on an external processor: <a href="https://twitter.com/Foone/status/1302453805057896448" rel="nofollow">https://twitter.com/Foone/status/1302453805057896448</a>',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T18:45:01.000Z',
      title: null,
      url: null,
      author: 'aspectmin',
      points: null,
      story_text: null,
      comment_text: 'This!',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33910091,
      created_at_i: 1670525101,
      _tags: ['comment', 'author_aspectmin', 'story_33907158'],
      objectID: '33911470',
      _highlightResult: {
        author: {
          value: 'aspectmin',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value: 'This!',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T18:43:39.000Z',
      title: null,
      url: null,
      author: 'ok_dad',
      points: null,
      story_text: null,
      comment_text:
        'Seeing as how it runs on a pregnancy test [0], I believe this is that list:<p>* ...<p>[0]: <a href="https:&#x2F;&#x2F;twitter.com&#x2F;foone&#x2F;status&#x2F;1302820468819288066" rel="nofollow">https:&#x2F;&#x2F;twitter.com&#x2F;foone&#x2F;status&#x2F;1302820468819288066</a> (This original was well below the fold on Google, shame on them.)',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33911150,
      created_at_i: 1670525019,
      _tags: ['comment', 'author_ok_dad', 'story_33907158'],
      objectID: '33911452',
      _highlightResult: {
        author: {
          value: 'ok_dad',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value:
            'Seeing as how it runs on a pregnancy test [0], I believe this is that list:<p>* ...<p>[0]: <a href="https://twitter.com/foone/status/1302820468819288066" rel="nofollow">https://twitter.com/foone/status/1302820468819288066</a> (This original was well below the fold on Google, shame on them.)',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T18:37:05.000Z',
      title: null,
      url: null,
      author: 'aidenn0',
      points: null,
      story_text: null,
      comment_text:
        'Those who do not study the reddit comment section are Doomed to repeat it?',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33910063,
      created_at_i: 1670524625,
      _tags: ['comment', 'author_aidenn0', 'story_33907158'],
      objectID: '33911370',
      _highlightResult: {
        author: {
          value: 'aidenn0',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value:
            'Those who do not study the reddit comment section are Doomed to repeat it?',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T18:25:39.000Z',
      title: null,
      url: null,
      author: 'barbazoo',
      points: null,
      story_text: null,
      comment_text:
        'Because not everyone sees the same posts. So I&#x27;m happy this came up again.',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33909619,
      created_at_i: 1670523939,
      _tags: ['comment', 'author_barbazoo', 'story_33907158'],
      objectID: '33911252',
      _highlightResult: {
        author: {
          value: 'barbazoo',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value:
            "Because not everyone sees the same posts. So I'm happy this came up again.",
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T18:24:15.000Z',
      title: null,
      url: null,
      author: 'Quinner',
      points: null,
      story_text: null,
      comment_text: 'Bah, humbug.',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33910063,
      created_at_i: 1670523855,
      _tags: ['comment', 'author_Quinner', 'story_33907158'],
      objectID: '33911235',
      _highlightResult: {
        author: {
          value: 'Quinner',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value: 'Bah, humbug.',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T18:22:36.000Z',
      title: null,
      url: null,
      author: 'jjordan',
      points: null,
      story_text: null,
      comment_text:
        'A lot of it is dumb luck. HN gets a lot of posts, most which see little to no activity. A few early upvotes seem to make all the difference in what eventually surfaces and what doesn&#x27;t.',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33909843,
      created_at_i: 1670523756,
      _tags: ['comment', 'author_jjordan', 'story_33907158'],
      objectID: '33911210',
      _highlightResult: {
        author: {
          value: 'jjordan',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value:
            "A lot of it is dumb luck. HN gets a lot of posts, most which see little to no activity. A few early upvotes seem to make all the difference in what eventually surfaces and what doesn't.",
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T18:18:07.000Z',
      title: null,
      url: null,
      author: 'Razengan',
      points: null,
      story_text: null,
      comment_text:
        'At this point it&#x27;s easier to just say what doesn&#x27;t play Doom.',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33907158,
      created_at_i: 1670523487,
      _tags: ['comment', 'author_Razengan', 'story_33907158'],
      objectID: '33911150',
      _highlightResult: {
        author: {
          value: 'Razengan',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value:
            "At this point it's easier to just say what doesn't play Doom.",
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T18:02:04.000Z',
      title: null,
      url: null,
      author: 'waltbosz',
      points: null,
      story_text: null,
      comment_text:
        'Does anyone have experience with Tinycircuits products? My 9-year-old daughter wants the TV and arcade for Christmas.<p>How hackable are they? I&#x27;m afraid it&#x27;s just going to become a toy she plays with for a day and gets bored.<p>...<p>Oh, also since this is a Doom post, I&#x27;ll selfishly mention that I always wish these ported-Doom-to-hardward-x projects would demo using the Ultimate Simpsons Doom 2 mod that I helped publish.\n<a href="https:&#x2F;&#x2F;doom.fandom.com&#x2F;wiki&#x2F;Ultimate_Simpsons_Doom" rel="nofollow">https:&#x2F;&#x2F;doom.fandom.com&#x2F;wiki&#x2F;Ultimate_Simpsons_Doom</a>',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33910754,
      created_at_i: 1670522524,
      _tags: ['comment', 'author_waltbosz', 'story_33907158'],
      objectID: '33910954',
      _highlightResult: {
        author: {
          value: 'waltbosz',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value:
            'Does anyone have experience with Tinycircuits products? My 9-year-old daughter wants the TV and arcade for Christmas.<p>How hackable are they? I\'m afraid it\'s just going to become a toy she plays with for a day and gets bored.<p>...<p>Oh, also since this is a Doom post, I\'ll selfishly mention that I always wish these ported-Doom-to-hardward-x projects would demo using the Ultimate Simpsons Doom 2 mod that I helped publish.\n<a href="https://doom.fandom.com/wiki/Ultimate_Simpsons_Doom" rel="nofollow">https://doom.fandom.com/wiki/Ultimate_Simpsons_Doom</a>',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T17:49:27.000Z',
      title: null,
      url: null,
      author: 'duneisagoodbook',
      points: null,
      story_text: null,
      comment_text:
        'Do we know what the minimum physical size is to run doom these days?',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33907158,
      created_at_i: 1670521767,
      _tags: ['comment', 'author_duneisagoodbook', 'story_33907158'],
      objectID: '33910815',
      _highlightResult: {
        author: {
          value: 'duneisagoodbook',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value:
            'Do we know what the minimum physical size is to run doom these days?',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T17:43:21.000Z',
      title: null,
      url: null,
      author: 'mc32',
      points: null,
      story_text: null,
      comment_text:
        'Reminds me of the Tinycircuits that have been posted here before: <a href="https:&#x2F;&#x2F;tinycircuits.com&#x2F;" rel="nofollow">https:&#x2F;&#x2F;tinycircuits.com&#x2F;</a>',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33907769,
      created_at_i: 1670521401,
      _tags: ['comment', 'author_mc32', 'story_33907158'],
      objectID: '33910754',
      _highlightResult: {
        author: {
          value: 'mc32',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value:
            'Reminds me of the Tinycircuits that have been posted here before: <a href="https://tinycircuits.com/" rel="nofollow">https://tinycircuits.com/</a>',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T17:25:26.000Z',
      title: null,
      url: null,
      author: 'bombcar',
      points: null,
      story_text: null,
      comment_text:
        'Yeah, I&#x27;d love the little ornament as is and would probably buy one, but the best &quot;it runs Doom&quot; are when it&#x27;s run on something clearly not designed for it (a printer, etc).',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33909146,
      created_at_i: 1670520326,
      _tags: ['comment', 'author_bombcar', 'story_33907158'],
      objectID: '33910529',
      _highlightResult: {
        author: {
          value: 'bombcar',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value:
            "Yeah, I'd love the little ornament as is and would probably buy one, but the best &quot;it runs Doom&quot; are when it's run on something clearly not designed for it (a printer, etc).",
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T16:51:21.000Z',
      title: null,
      url: null,
      author: 'Yahivin',
      points: null,
      story_text: null,
      comment_text: 'Ok, now network them.',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33907158,
      created_at_i: 1670518281,
      _tags: ['comment', 'author_Yahivin', 'story_33907158'],
      objectID: '33910091',
      _highlightResult: {
        author: {
          value: 'Yahivin',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value: 'Ok, now network them.',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T16:49:31.000Z',
      title: null,
      url: null,
      author: 'kennyadam',
      points: null,
      story_text: null,
      comment_text:
        'Nice reddit-tier comment - couldn&#x27;t think of a pun too?',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33908351,
      created_at_i: 1670518171,
      _tags: ['comment', 'author_kennyadam', 'story_33907158'],
      objectID: '33910063',
      _highlightResult: {
        author: {
          value: 'kennyadam',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value: "Nice reddit-tier comment - couldn't think of a pun too?",
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T16:31:57.000Z',
      title: null,
      url: null,
      author: 'northerdome',
      points: null,
      story_text: null,
      comment_text: 'A very foone Christmas!',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33907158,
      created_at_i: 1670517117,
      _tags: ['comment', 'author_northerdome', 'story_33907158'],
      objectID: '33909808',
      _highlightResult: {
        author: {
          value: 'northerdome',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value: 'A very foone Christmas!',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T15:58:55.000Z',
      title: null,
      url: null,
      author: 'kridsdale1',
      points: null,
      story_text: null,
      comment_text:
        'IIRC there was a WAD file that added Santa hats to all the enemies. Probably had festive weapons too. It’s been 25+ years.',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33908768,
      created_at_i: 1670515135,
      _tags: ['comment', 'author_kridsdale1', 'story_33907158'],
      objectID: '33909304',
      _highlightResult: {
        author: {
          value: 'kridsdale1',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value:
            'IIRC there was a WAD file that added Santa hats to all the enemies. Probably had festive weapons too. It’s been 25+ years.',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T15:52:57.000Z',
      title: null,
      url: null,
      author: 'nine_k',
      points: null,
      story_text: null,
      comment_text:
        'Ironically, the original IBM PC was of course completely incapable of running Doom. You needed an AT with at least a 386, and preferably a 486.',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33908479,
      created_at_i: 1670514777,
      _tags: ['comment', 'author_nine_k', 'story_33907158'],
      objectID: '33909207',
      _highlightResult: {
        author: {
          value: 'nine_k',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value:
            'Ironically, the original IBM PC was of course completely incapable of running Doom. You needed an AT with at least a 386, and preferably a 486.',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T15:49:22.000Z',
      title: null,
      url: null,
      author: 'yreg',
      points: null,
      story_text: null,
      comment_text:
        'Well, no. bombcar wants it to be a hack on a device that has a different purpose intended by its makers.',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33908395,
      created_at_i: 1670514562,
      _tags: ['comment', 'author_yreg', 'story_33907158'],
      objectID: '33909146',
      _highlightResult: {
        author: {
          value: 'yreg',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value:
            'Well, no. bombcar wants it to be a hack on a device that has a different purpose intended by its makers.',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T15:46:33.000Z',
      title: null,
      url: null,
      author: 'yreg',
      points: null,
      story_text: null,
      comment_text: 'This is unreasonably cute.',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33907158,
      created_at_i: 1670514393,
      _tags: ['comment', 'author_yreg', 'story_33907158'],
      objectID: '33909105',
      _highlightResult: {
        author: {
          value: 'yreg',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value: 'This is unreasonably cute.',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
    {
      created_at: '2022-12-08T15:46:10.000Z',
      title: null,
      url: null,
      author: 'zoomablemind',
      points: null,
      story_text: null,
      comment_text:
        'Not that far away from the  TV commercials of some major hardware store running in this season and advertizing chain-saws, drills, and lawn-mowers nicely wrapped under the Xmas tree...',
      num_comments: null,
      story_id: 33907158,
      story_title: 'A Christmas tree bauble that plays Doom',
      story_url: 'https://spritesmods.com/?art=doom-bauble&page=1',
      parent_id: 33908768,
      created_at_i: 1670514370,
      _tags: ['comment', 'author_zoomablemind', 'story_33907158'],
      objectID: '33909101',
      _highlightResult: {
        author: {
          value: 'zoomablemind',
          matchLevel: 'none',
          matchedWords: [],
        },
        comment_text: {
          value:
            'Not that far away from the  TV commercials of some major hardware store running in this season and advertizing chain-saws, drills, and lawn-mowers nicely wrapped under the Xmas tree...',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_title: {
          value: 'A Christmas tree bauble that plays Doom',
          matchLevel: 'none',
          matchedWords: [],
        },
        story_url: {
          value: 'https://spritesmods.com/?art=doom-bauble&page=1',
          matchLevel: 'none',
          matchedWords: [],
        },
      },
    },
  ],
  nbHits: 32,
  page: 0,
  nbPages: 2,
  hitsPerPage: 20,
  exhaustiveNbHits: true,
  exhaustiveTypo: true,
  exhaustive: {
    nbHits: true,
    typo: true,
  },
  query: '',
  params:
    'advancedSyntax=true&analytics=true&analyticsTags=backend&tags=comment%2Cstory_33907158',
  processingTimeMS: 1,
  processingTimingsMS: {
    total: 1,
  },
};
